import React, { useCallback, useEffect, useMemo, useState } from "react";
import api from "../api";

const MODE_LABELS = { focus: "Focus mode", sprint: "Sprint review", team: "Team operations", briefing: "Daily briefing" };

export default function BriefingPresentation({ mode, user, boards, activeBoard, githubConnected, onComplete }) {
  const [started, setStarted] = useState(false); const [muted, setMuted] = useState(false); const [index, setIndex] = useState(0); const [data, setData] = useState({ todos: [], utilization: null });
  useEffect(() => { let live = true; Promise.all([Promise.all(boards.map((board) => api.get("/todos", { params: { boardId: board._id } }).then(({ data: todos }) => todos))).catch(() => []), api.get("/utilization").then(({ data: utilization }) => utilization).catch(() => null)]).then(([groups, utilization]) => { if (live) setData({ todos: groups.flat(), utilization }); }); return () => { live = false; window.speechSynthesis?.cancel(); }; }, [boards]);
  const slides = useMemo(() => {
    const open = data.todos.filter((todo) => !todo.completed); const done = data.todos.length - open.length; const overdue = open.filter((todo) => todo.reminderDateTime && new Date(todo.reminderDateTime) < new Date()).length; const blocked = open.filter((todo) => todo.blockedReason).length; const activeSprints = boards.flatMap((board) => (board.sprints || []).filter((sprint) => sprint.status === "active")); const overloaded = data.utilization?.members?.filter((member) => member.utilization > 1).length || 0;
    const intro = { code: "INITIALIZING", title: MODE_LABELS[mode], metric: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }), body: `Welcome ${user?.name?.split(" ")[0] || "Operator"}. Preparing your ${MODE_LABELS[mode].toLowerCase()}.` };
    const workload = { code: "WORKLOAD", title: "Current delivery state", metric: `${open.length} OPEN`, body: `${done} items are complete. ${overdue} are overdue and ${blocked} are blocked.` };
    if (mode === "focus") return [intro, { code: "PRIORITY", title: activeBoard?.name || "Current board", metric: `${open.filter((todo) => String(todo.board) === String(activeBoard?._id)).length} TASKS`, body: "The interface will reduce secondary telemetry and prioritize current work, reminders, and the delivery timeline." }, workload];
    if (mode === "sprint") return [intro, { code: "SPRINT STATUS", title: "Active delivery cycles", metric: `${activeSprints.length} ACTIVE`, body: activeSprints.length ? "Sprint goals, completion, blockers, and engineering activity are ready for review." : "No sprint is active. Open the workspace to start a planned sprint." }, workload];
    if (mode === "team") return [intro, { code: "CAPACITY", title: "Resource allocation", metric: data.utilization ? `${Math.round(data.utilization.totals.utilization * 100)}%` : "PENDING", body: `${overloaded} resources are currently above calculated capacity. Team workload and engineering telemetry will be emphasized.` }, workload];
    return [intro, workload, { code: "SYSTEMS", title: "Connected intelligence", metric: githubConnected ? "ONLINE" : "PARTIAL", body: `GitHub is ${githubConnected ? "connected" : "offline"}. ${overloaded} resource warnings and ${activeSprints.length} active sprints were detected.` }];
  }, [activeBoard, boards, data, githubConnected, mode, user]);

  const finish = useCallback(() => { window.speechSynthesis?.cancel(); sessionStorage.setItem(`karmex-briefed-${mode}`, "1"); onComplete(); }, [mode, onComplete]);
  useEffect(() => { if (!started) return undefined; const slide = slides[index]; if (!muted && window.speechSynthesis) { window.speechSynthesis.cancel(); const speech = new SpeechSynthesisUtterance(`${slide.title}. ${slide.metric}. ${slide.body}`); speech.rate = .95; speech.pitch = .9; window.speechSynthesis.speak(speech); } const timer = setTimeout(() => { if (index < slides.length - 1) setIndex((value) => value + 1); else finish(); }, 5200); return () => clearTimeout(timer); }, [finish, index, muted, slides, started]);
  if (!started) return <div className="briefing-stage"><div className="briefing-core"><span className="briefing-orbit" /><span className="eyebrow">VOICE BRIEFING READY</span><h1>{MODE_LABELS[mode]}</h1><p>Karmex Intelligence will present your live summary, then configure the dashboard for this operating mode.</p><button type="button" className="accent-btn" onClick={() => setStarted(true)}>Begin briefing</button><button type="button" className="briefing-skip" onClick={finish}>Enter silently</button></div></div>;
  const slide = slides[index];
  return <div className="briefing-stage active"><header><span>KARMEX INTELLIGENCE</span><div><button type="button" onClick={() => { setMuted(!muted); window.speechSynthesis?.cancel(); }}>{muted ? "Enable voice" : "Mute voice"}</button><button type="button" onClick={finish}>Skip briefing</button></div></header><main><span className="briefing-code">{slide.code}</span><h1>{slide.title}</h1><strong>{slide.metric}</strong><p>{slide.body}</p><div className="briefing-progress">{slides.map((item, slideIndex) => <i key={item.code} className={slideIndex <= index ? "active" : ""} />)}</div></main><footer>{index + 1} / {slides.length}</footer></div>;
}
